application: chrome-experience-sampling
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: survey_backend_api.APPLICATION

libraries:
- name: endpoints
  version: latest
