application: chrome-experience-sampling
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# webapp2 handler for homepage
#- url: /
  #script: home.APPLICATION
# Endpoints handler
- url: /_ah/spi/.*
  script: survey_backend_api.APPLICATION

libraries:
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest

