application: chrome-experience-sampling
version: v1r2
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: survey_backend_api.APPLICATION

libraries:
- name: endpoints
  version: latest
- name: webapp2
  version: latest

admin_console:
  pages:
  - name: Data Export
    url: /export
